/**
 * Export/Import Utility Library
 * 
 * Provides functions to export notes to various formats (TXT, MD, PDF)
 * and import notes from TXT/MD files.
 */

interface Note {
  _id?: string;
  title: string;
  content: string;
  summary?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * Export note as plain text file
 */
export const exportAsTxt = (note: Note): void => {
  const content = `${note.title}\n${'='.repeat(note.title.length)}\n\n${note.content}${
    note.summary ? `\n\n---\nSummary: ${note.summary}` : ''
  }\n\n---\nCreated: ${note.createdAt ? new Date(note.createdAt).toLocaleString() : 'N/A'}`;

  downloadFile(content, `${sanitizeFileName(note.title)}.txt`, 'text/plain');
};

/**
 * Export note as Markdown file
 */
export const exportAsMarkdown = (note: Note): void => {
  const content = `# ${note.title}

${note.content}

${note.summary ? `---

## Summary

${note.summary}

` : ''}---

**Created:** ${note.createdAt ? new Date(note.createdAt).toLocaleString() : 'N/A'}  
**Last Updated:** ${note.updatedAt ? new Date(note.updatedAt).toLocaleString() : 'N/A'}`;

  downloadFile(content, `${sanitizeFileName(note.title)}.md`, 'text/markdown');
};

/**
 * Export note as PDF using client-side generation
 */
export const exportAsPdf = async (note: Note): Promise<void> => {
  // Dynamic import to reduce bundle size
  const html2pdf = (await import('html2pdf.js')).default;

  const htmlContent = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto;">
      <h1 style="color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px;">
        ${escapeHtml(note.title)}
      </h1>
      
      <div style="color: #666; font-size: 12px; margin-bottom: 30px;">
        <strong>Created:</strong> ${note.createdAt ? new Date(note.createdAt).toLocaleString() : 'N/A'} &nbsp;|&nbsp;
        <strong>Updated:</strong> ${note.updatedAt ? new Date(note.updatedAt).toLocaleString() : 'N/A'}
      </div>
      
      <div style="line-height: 1.8; color: #333; white-space: pre-wrap; margin-bottom: 30px;">
        ${escapeHtml(note.content)}
      </div>
      
      ${note.summary ? `
        <div style="background-color: #eff6ff; border-left: 4px solid #3b82f6; padding: 20px; margin-top: 30px; border-radius: 4px;">
          <h3 style="color: #1e40af; margin-top: 0; margin-bottom: 10px;">📝 Summary</h3>
          <p style="margin: 0; color: #1e3a8a; line-height: 1.6;">${escapeHtml(note.summary)}</p>
        </div>
      ` : ''}
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 11px; text-align: center;">
        Generated by AI Note App
      </div>
    </div>
  `;

  const options = {
    margin: 0.5,
    filename: `${sanitizeFileName(note.title)}.pdf`,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in' as const, format: 'letter' as const, orientation: 'portrait' as const }
  };

  try {
    await html2pdf().set(options).from(htmlContent).save();
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF');
  }
};

/**
 * Export multiple notes as a single file
 */
export const exportMultipleNotes = (notes: Note[], format: 'txt' | 'md'): void => {
  let content = '';
  const timestamp = new Date().toISOString().split('T')[0];

  if (format === 'md') {
    content = `# My Notes Collection\n\n*Exported on ${new Date().toLocaleString()}*\n\n---\n\n`;
    notes.forEach((note, index) => {
      content += `## ${index + 1}. ${note.title}\n\n${note.content}\n\n`;
      if (note.summary) {
        content += `**Summary:** ${note.summary}\n\n`;
      }
      content += `*Created: ${note.createdAt ? new Date(note.createdAt).toLocaleString() : 'N/A'}*\n\n---\n\n`;
    });
  } else {
    content = `MY NOTES COLLECTION\n${'='.repeat(50)}\n\nExported on ${new Date().toLocaleString()}\n\n`;
    notes.forEach((note, index) => {
      content += `\n${'='.repeat(50)}\n${index + 1}. ${note.title}\n${'='.repeat(50)}\n\n${note.content}\n\n`;
      if (note.summary) {
        content += `Summary: ${note.summary}\n\n`;
      }
      content += `Created: ${note.createdAt ? new Date(note.createdAt).toLocaleString() : 'N/A'}\n`;
    });
  }

  const extension = format === 'md' ? 'md' : 'txt';
  const mimeType = format === 'md' ? 'text/markdown' : 'text/plain';
  downloadFile(content, `notes-export-${timestamp}.${extension}`, mimeType);
};

/**
 * Import note from text file
 */
export const importFromFile = (file: File): Promise<Partial<Note>> => {
  return new Promise((resolve, reject) => {
    if (!file.name.match(/\.(txt|md|markdown)$/i)) {
      reject(new Error('Only .txt, .md, or .markdown files are supported'));
      return;
    }

    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsed = parseImportedContent(content, file.name);
        resolve(parsed);
      } catch (error) {
        reject(error);
      }
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsText(file);
  });
};

/**
 * Parse imported file content
 */
const parseImportedContent = (content: string, fileName: string): Partial<Note> => {
  const lines = content.split('\n');
  let title = '';
  let noteContent = '';
  let inContent = false;

  // Try to extract title from first line or filename
  if (lines[0] && (lines[0].startsWith('#') || lines[0].trim().length > 0)) {
    title = lines[0].replace(/^#+\s*/, '').trim();
    inContent = true;
    
    // Skip title and any underline/separator
    let startIndex = 1;
    if (lines[1] && (lines[1].match(/^[=\-]+$/) || lines[1].trim() === '')) {
      startIndex = 2;
    }
    
    noteContent = lines.slice(startIndex).join('\n').trim();
  } else {
    // Use filename as title
    title = fileName.replace(/\.(txt|md|markdown)$/i, '');
    noteContent = content.trim();
  }

  // Remove metadata sections (like "Created:", "Summary:", etc.)
  noteContent = noteContent.replace(/\n---\n[\s\S]*$/g, '').trim();

  return {
    title: title || 'Imported Note',
    content: noteContent || 'No content found',
  };
};

/**
 * Helper function to download a file
 */
const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Sanitize filename for safe file system usage
 */
const sanitizeFileName = (filename: string): string => {
  return filename
    .replace(/[^a-z0-9]/gi, '_')
    .replace(/_+/g, '_')
    .substring(0, 50);
};

/**
 * Escape HTML special characters
 */
const escapeHtml = (text: string): string => {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
};
